[package]
name = "mysteriousbot"
version = "0.1.0"
authors = ["Christopher R. Miller <xpm@mysteriouspants.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.41"
dotenv = "0.15.0"
futures = "0.3.8"
lazy_static = "1.4.0"
pickledb = "0.4.1"
regex = "1.4.2"
serenity = { version = "0.9.1", default-features = false, features = [ "builder", "cache", "client", "gateway", "http", "model", "utils", "rustls_backend" ] }
thiserror = "1.0.22"
tokio = { version = "0.3.3", features = [ "macros", "rt", "rt-multi-thread" ] }
tokio-compat-02 = "0.1.2" # can drop when serenity upgrades to tokio 0.3
toml = "0.5.7"
