[package]
name = "mysteriousbot"
version = "0.1.0"
authors = ["Christopher R. Miller <xpm@mysteriouspants.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
lazy_static = "1.4.0"
pickledb = "0.4.1"
regex = "1.3.9"
serenity = "0.8.7"
toml = "0.5.6"
