# Bot Testing Playground
[[guilds.728474842877263902.slash_responders]]
command = "wednesday"
description = "it is wednesday my doods"
response = "https://www.idevgames.com/its_wednesday_my_doods.mp4"

[[guilds.728474842877263902.slash_responders]]
command = "friday"
description = "mufasa, it's friday then"
response = "https://www.idevgames.com/its_friday_then.mp4"

[[guilds.728474842877263902.slash_responders]]
command = "bus"
description = "another one rides the bus"
response = ":musical_score::musical_note: Another one rides the bus! :notes:"

[[guilds.728474842877263902.autoemojis]]
on = { mention = 249051133987913728 } # Necrothitude
twemojis = [ "swedishfish"]
#                    #general
only_in_channels = [ 732783069823762453 ]

# iDevGames
[[guilds.488890763720130560.slash_responders]]
command = "wednesday"
description = "it is wednesday my doods"
response = "https://www.idevgames.com/its_wednesday_my_doods.mp4"

[[guilds.488890763720130560.slash_responders]]
command = "friday"
description = "mufasa, it's friday then"
response = "https://www.idevgames.com/its_friday_then.mp4"

[[guilds.488890763720130560.slash_responders]]
command = "bus"
description = "another one rides the bus"
response = ":musical_score::musical_note: Another one rides the bus! :notes:"

# RECON/B0T
[[guilds.499288051290210312.slash_responders]]
command = "wednesday"
description = "it is wednesday my doods"
response = "https://www.idevgames.com/its_wednesday_my_doods.mp4"

[[guilds.499288051290210312.slash_responders]]
command = "friday"
description = "mufasa, it's friday then"
response = "https://www.idevgames.com/its_friday_then.mp4"

[[guilds.499288051290210312.autoemojis]]
on = { mention = 261559920485335040 } # P33ky
twemojis = [ "pingsock"]
#                    #alliance           #nsfw
only_in_channels = [ 499363186957352970, 499363309070319616 ]

[[guilds.499288051290210312.autoemojis]]
on = { message = 139425197118849025 } # Skorpion Medion
twemojis = [ "swedishfish"]
#                    #alliance           #nsfw
only_in_channels = [ 499363186957352970, 499363309070319616 ]

# Aurora Dynamics
[[guilds.792112275473301576.autoemojis]]
on = { mention = 261559920485335040 } # P33ky
twemojis = [ "PingBad" ]
#                    #corp-chat          # industry          #commerce-shopping  #transports-r-us    #token-proof        #keep-star          #general            #shitpost-central   #games              #music              #food-related       #eve-news           #wheres-daddy-today
only_in_channels = [ 792116253954932776, 792696740234395648, 792116632872419338, 881323330425212969, 917563911790800936, 918485978128187423, 792112359215726602, 874511358668972093, 803049246043275294, 832285540019077180, 859993967319842847, 878233071546171422, 872020091976433674 ]

[[guilds.792112275473301576.autoemojis]]
on = { message = 249051133987913728 } # Necrothitude
twemojis = [ "pepetoilet" ]
#                    #shitpost-central
only_in_channels = [ 874511358668972093 ]

[[guilds.792112275473301576.slash_responders]]
command = "wednesday"
description = "it is wednesday my doods"
response = "https://www.idevgames.com/its_wednesday_my_doods.mp4"

[[guilds.792112275473301576.slash_responders]]
command = "friday"
description = "mufasa, it's friday then"
response = "https://www.idevgames.com/its_friday_then.mp4"

[[guilds.792112275473301576.slash_responders]]
command = "bus"
description = "another one rides the bus"
response = ":musical_score::musical_note: Another one rides the bus! :notes:"
