---
guilds:
  # bot testing playground
  728474842877263902:
    commands:
      - &wednesday
        alias: wednesday
        description: "it is wednesday my doods"
        reply_messages:
          - https://cdn.discordapp.com/attachments/874511358668972093/963863870387142717/its_wednesday_my_doods.mp4
          - https://cdn.discordapp.com/attachments/874511358668972093/991766704097079306/05a55213c600498578a6a188a9fd48ba.mp4
          - https://cdn.discordapp.com/attachments/874511358668972093/989242891014664192/66adb14c6961d4fd3e1b0564f037a9a8.mp4
          - https://cdn.discordapp.com/attachments/874511358668972093/989242890637152336/09de45ecffbfb78eb88451a2601dd8c0.mp4
          - https://cdn.discordapp.com/attachments/874511358668972093/989242890310017024/ce5fa91d241b288371f0a4ff5771058f.mp4
          - https://cdn.discordapp.com/attachments/874511358668972093/1001850949066829844/349e62b82a6b0b0456a116dc0d649662.mp4
      - &friday
        alias: friday
        description: "mufasa, it's friday then"
        reply_messages:
          - "https://cdn.discordapp.com/attachments/874511358668972093/964587359637233674/Mufasa-_its_friday_then.mp4"
          - "https://cdn.discordapp.com/attachments/874511358668972000/987461620148109352/redditsave.com_maybe_maybe_maybe-zfk0quiebfw61.mp4"
          - "https://cdn.discordapp.com/attachments/874511358668972093/984888605426221056/09b0f74e14017467a5d7f990229e96d2.mp4"
          - "https://cdn.discordapp.com/attachments/874511358668972093/984888604855762974/b9f2ae6cb8642cca7e306aa7ca66d677.mp4"
          - "https://cdn.discordapp.com/attachments/874511358668972093/984888603580706838/WhatsApp_Video_2021-03-05_at_10.23.54.mp4"
      - &freedom
        alias: freedom
        description: your freedom-loving meme/video dispener. duplicates expected if you do it too much lol
        reply_messages:
          - https://www.youtube.com/watch?v=FHe_VHT4ojo # NATO Doctrine
          - https://www.youtube.com/watch?v=8b5rIFci5vs # NATOWAVE
          - https://www.youtube.com/watch?v=QRlqJFdb6ZY # NATOWAVE.mp4
          - https://www.youtube.com/watch?v=vUFGWDlVh_Y # Exercise NATOWAVE
          - https://www.youtube.com/watch?v=D7Yp95BCrJ8 # Liberty by Fire NATOWAVE
          - https://www.youtube.com/watch?v=d0Xol9ubNGE # NATO November
          - https://www.youtube.com/watch?v=-YJy6r-ZKlE # NATO Imperative NATOWAVE
          - https://www.youtube.com/watch?v=GceP66tJL60 # The Coldest Conflict NATOWAVE
          - https://www.youtube.com/watch?v=7Lcx8YtOEfU # War in the Gulf NATOWAVE Edition
          - https://www.youtube.com/watch?v=LNUMTgxYN4Y # At;amtoc Community NATOWAVE
          - https://www.youtube.com/watch?v=2tXu9s9q1DU # NATO Little Dark Age
          - https://www.youtube.com/watch?v=BevT42dGYmo # NATOWAVE
          - https://www.youtube.com/watch?v=E-7YboIRv1I # NATO/Germany - My Little Nightmare
          - https://www.youtube.com/watch?v=XGcADQdlmCk # NATOWAVE - Superiority at Sea
          - https://www.youtube.com/watch?v=MGKnc_YiR-E # The Battle Cry of Freedom
          - https://www.youtube.com/watch?v=OFtNVEbasOo # Battle Hymn of the Republic
          - https://www.youtube.com/watch?v=7Os7Z94UYa4 # Over the Hills and Far Away
          - https://www.youtube.com/watch?v=MmcKPVndlTg # Men of Harlech
          - https://cdn.discordapp.com/attachments/318603903220318210/1008190981432164352/Russia_and_China_take_notes_bvwa7tqblag91.mp4
          - https://cdn.discordapp.com/attachments/808536952571297855/1006107344121381004/unknown.png
          - https://cdn.discordapp.com/attachments/808536952571297855/1004250400158928996/unknown.png
          - https://cdn.discordapp.com/attachments/951165912164233256/1008225629101101087/IFESFpr.jpg
          - https://cdn.discordapp.com/attachments/951165912164233256/1008225738232713266/polandball_north_america.png
      - &bus
        alias: bus
        description: another one rides the bus
        reply_messages: |-
          :musical_score::musical_note: Another one rides the bus! :notes:
      - alias: leaderboard
        description: prints a leaderboard
        counter_leaderboard: test_counter
      - alias: pingboard
        description: who has pinged our tame ceo the most?
        counter_leaderboard: peeky_ping_count
      - alias: curseboard
        description: do you kiss your mother with that mouth?
        counter_leaderboard: verbal_morality_statute
      - alias: fax
        description: Give a quarter, get a quote. Probably not what you want.
        reply_messages:
          - |
            **2022-11-12 10:14 AM PST**
            <TheCire> Ugh I want to get out of bed but it's so cold...
            <mysteriouspants> Can't poop in bed unless you're Amber Heard.
          - |
            **2020-10-01 7:03 PM EST**
            <NCarter> What it needs first of all is a pair of spatulas jammed into its underside.
            <NCarter> I've done this multiple times and it's always awful.
    autoresponders:
      # respond to certain messages with the famous copypasta for comedy
      - &wank
        message_matches: "(?i)\\b(wank|cum|masturbate)\\b"
        reply_messages: "https://cdn.discordapp.com/attachments/568671549951836161/962560285732917248/New_Rule.mp4"
        cooldown: &thirtyminutes 1800
        counter: test_counter
      - &clarus 
        message_matches: ":clarus:"
        reply_messages: "Moof!"
        cooldown: 300
      - &minecraft
        message_matches: "(?i)\\b(minecraft)\\b"
        reply_messages: "https://cdn.discordapp.com/attachments/874511358668972093/959864645697536121/Video.mov"
        cooldown: *thirtyminutes
      - &boats
        message_matches: "(?i)\\b(boats?|ships?)\\b"
        reply_message:
          - https://cdn.discordapp.com/attachments/951165912164233256/999902514046578719/i_like_boats.mp4
          - https://cdn.discordapp.com/attachments/951165912164233256/999902515141279764/i_like_boats_window_crash.mp4
        cooldown: *thirtyminutes
      - &hair
        message_matches: "(?i)\\b(hair)\\b"
        reply_message: https://cdn.discordapp.com/attachments/951165912164233256/999902514533126174/quinnypig_is_the_prettiest_pony.mp4
        cooldown: *thirtyminutes
  
  # RECON/B0T
  499288051290210312:
    commands:
      - *wednesday
      - *friday
      - *freedom
    autoresponders:
      - user_message: 139425197118849025 # Skorpion Medion
        twemojis: swedishfish
        only_in_channels:
          - 499363186957352970 #alliance
          - 499363309070319616 #nsfw
            
  # Aurora Dynamics
  792112275473301576:
    commands:
      - *wednesday
      - *friday
      - *bus
      - *freedom
      - alias: ehehehe
        description: peeky's diabolical laugh
        reply_messages: https://cdn.discordapp.com/attachments/792116253954932776/1001842590833975306/Ehehehe_1.mp4
      # - alias: pingboard
      #   description: who has pinged our tame ceo the most?
      #   counter_leaderboard: peeky_ping_count
      - alias: curseboard
        description: do you kiss your mother with that mouth?
        counter_leaderboard: verbal_morality_statute
    autoresponders:
      # - *wank
      - user_mentioned: 261559920485335040 # P33ky
        twemojis: PingBad
        counter: peeky_ping_count
        only_in_channels: &a0ra_member_channels
          - 792116253954932776 #corp-chat
          - 1023766622097375322 #krabs-anonymous
          - 1130486559020425318 #scanning
          - 792696740234395648 #industry
          - 1162101259675898017 #questions
          - 971051680110116874 #fits
          - 1159489586481864765 #ministry-of-truth

          - 792116632872419338 #shopping
          - 881323330425212969 #transports-r-us
          - 1006141830519337031 #stim-zone

          - 1130915215593197698 #group-vouch
          - 1151093814170234880 #the-suggestion-box

          - 792112359215726602 #general
          - 1128024155535720478 #pets
          - 874511358668972093 #shitpost-central
          - 803049246043275294 #games
          - 832285540019077180 #music
          - 859993967319842847 #food
          - 878233071546171422 #eve-news

          - 946406061554950164 #real-life-stuff-talk
          - 1094333510724108288 #vega-bonde-memorial-room-of-weeb
          - 878665824745947156 #nsfw
      - message_matches: "(?i)\\b(nascar)\\b"
        reply_messages: "https://cdn.discordapp.com/attachments/874511358668972093/958491000555323462/Image.gif"
        only_in_channels: *a0ra_member_channels
        cooldown: *thirtyminutes
      - message_matches: "(?i)\\b(finland)\\b"
        reply_messages: "https://cdn.discordapp.com/attachments/732783069823762453/968032292725469184/unknown.png"
        only_in_channels: *a0ra_member_channels
        cooldown: *thirtyminutes
      - message_matches: "(?i)\\b(007|james bond)\\b"
        reply_messages: "https://cdn.discordapp.com/attachments/874511358668972093/965119313843458048/image0.jpg"
        only_in_channels: *a0ra_member_channels
        cooldown: *thirtyminutes
      - message_matches: "(?i)\\b(nag|naglfar)\\b"
        reply_messages: "https://cdn.discordapp.com/attachments/792116253954932776/968738866532085791/unknown.png"
        only_in_channels: *a0ra_member_channels
        cooldown: *thirtyminutes
      - message_matches: "(?i)\\b(minecraft)\\b"
        reply_messages: "https://cdn.discordapp.com/attachments/874511358668972093/959864645697536121/Video.mov"
        cooldown: *thirtyminutes
        only_in_channels: *a0ra_member_channels
      - message_matches: "(?i):poop:"
        reply_messages: "https://cdn.discordapp.com/attachments/874511358668972093/964602000710959215/Video.mov"
        cooldown: *thirtyminutes
        only_in_channels: *a0ra_member_channels
      - &boats
        message_matches: "(?i)\\b(boats?|ships?)\\b"
        reply_message:
          - https://cdn.discordapp.com/attachments/951165912164233256/999902514046578719/i_like_boats.mp4
          - https://cdn.discordapp.com/attachments/951165912164233256/999902515141279764/i_like_boats_window_crash.mp4
        cooldown: *thirtyminutes
        only_in_channels: *a0ra_member_channels
      - &hair
        message_matches: "(?i)\\b(hair)\\b"
        reply_message: https://cdn.discordapp.com/attachments/951165912164233256/999902514533126174/quinnypig_is_the_prettiest_pony.mp4
        cooldown: *thirtyminutes
        only_in_channels: *a0ra_member_channels
      - message_matches:
          # standard american
          - "(?i)\\b(damn|shit|shitty|fuck|fucking|ass|asshole|bastard|bitch|fucker|cuck|motherfucker|slut|whore|kurwa|pussy)\\b"
          # chiefly british
          - "(?i)\\b(cunt|twat|bugger|wanker|bor+is johnson|arse|arsehole|cuntbag|plonker|prick|bollocks|bint|prat|tosser|pillock|nob|bel+end)\\b"
          # CJ and Killer said these, I had no idea
          - "(?i)\\b(gash|cheffed|pissflaps|shitbag|cocknose|wankstain|arsebadger|jizz|cock|cum|thundercunt|nonce|cumwipe|minger)\\b"
          # Keef joined our diccord and said this immediately. I'm so sorry.
          - "(?i)\\b(fagg?ot)\\b"
          # EVE Online/meme words
          - "(?i)\\b(french|france|gallente|dick|dickhead|mittani|goons?|goonswarm)\\b"
        twemojis: getsomehelp
        cooldown: 0
        only_in_channels: *a0ra_member_channels
        counter: verbal_morality_statute

  # iDevGames
  488890763720130560:
    autoresponders:
      - *clarus
      - message_matches: "(?i)(\\b|_)(meep)(\\b|_)"
        twemojis: clarus
